## Copyright © 2020, Oracle and/or its affiliates.
## All rights reserved. The Universal Permissive License (UPL), Version 1.0 as shown at http://oss.oracle.com/licenses/upl

    title: "OCI Data Flow"
    stackDescription: Deploy OCI Data Flow and related resources
    schemaVersion: 1.1.0
    version: "20190404"
    locale: "en"

    variableGroups:
    - title: General Configuration
      visible: false
      variables:
      - tenancy_ocid
      - release

    - title: General Configuration
      visible: true
      variables:
      - compartment_ocid
      - region
      - deploy_demo_application
      - show_advanced

    - title: Bucket Configuration
      visible: true
      variables:
      - dataflow_warehouse_bucket_name
      - dataflow_warehouse_bucket_access_type
      - dataflow_warehouse_bucket_storage_tier
      - dataflow_logs_bucket_name
      - dataflow_logs_bucket_access_type
      - dataflow_logs_bucket_storage_tier

    - title: Administrators Group - IAM Configuration
      visible: true
      variables:
      - dataflow_admins_group_name
      - dataflow_admins_group_description
      - dataflow_admins_policy_name
      - dataflow_admins_policy_description

    - title: Users Group - IAM Configuration
      visible: true
      variables:
      - dataflow_users_group_name
      - dataflow_users_group_description
      - dataflow_users_policy_name
      - dataflow_users_policy_description

    - title: Advanced Configuration
      visible: show_advanced
      variables:
      - application_file_uri
      - arguments
      - application_archive_uri
      - application_display_name
      - application_driver_shape
      - application_executor_shape
      - application_language
      - application_num_executors
      - application_spark_version

    variables:
  
      show_advanced:
        type: boolean
        title: "Show advanced options?"
        description: "Shows advanced options."
        visible: true
        default: false
      
      deploy_demo_application:
        type: boolean
        required: true
        title: Deploy demo application?
        description: Deploys a demo Python Spark application

      compartment_ocid:
        type: oci:identity:compartment:id
        required: true
        title: Compartment
        description: Compartment where you want to create the solution resources

      region:
        type: oci:identity:region:name
        required: true
        title: Region
        description: Region where you want to deploy the resources defined by this stack

      dataflow_warehouse_bucket_name:
        type: string
        required: true
        title: "Bucket Name"
        description: "Name of the bucket"

      dataflow_warehouse_bucket_access_type:
        type: enum
        required: true
        title: "Access Type"
        description: "Choose the type of access for the backup bucket"
        enum:
          - "NoPublicAccess"
          - "Public"

      dataflow_warehouse_bucket_storage_tier:
        type: enum
        required: true
        title: "Storage Tier"
        description: "Select the tier for the backup bucket"
        enum:
          - "Standard"

      dataflow_logs_bucket_name:
        type: string
        required: true
        title: "Bucket Name"
        description: "Name of the bucket"

      dataflow_logs_bucket_access_type:
        type: enum
        required: true
        title: "Access Type"
        description: "Choose the type of access for the backup bucket"
        enum:
          - "NoPublicAccess"
          - "Public"

      dataflow_logs_bucket_storage_tier:
        type: enum
        required: true
        title: "Storage Tier"
        description: "Select the tier for the backup bucket"
        enum:
          - "Standard"
        
      dataflow_admins_group_name:
        type: string
        required: true
        title: "Group Name"
        description: "Name of the Data Flow administrator group "

      dataflow_admins_group_description:
        type: string
        required: true
        title: "Group Description"
        description: "Data Flow administrators group Description"

      dataflow_admins_policy_name:
        type: string
        required: true
        title: "Policy Name"
        description: "Data Flow administrator Policy name"

      dataflow_admins_policy_description:
        type: string
        required: true
        title: "Policy Description"
        description: "Description of the Data Flow administrator policy"

      dataflow_users_group_name:
        type: string
        required: true
        title: "Group Name"
        description: "Name of the Data Flow users group"

      dataflow_users_group_description:
        type: string
        required: true
        title: "Group Description"
        description: "Data Flow users group Description"

      dataflow_users_policy_name:
        type: string
        required: true
        title: "Policy Name"
        description: "Data Flow users Policy name"

      dataflow_users_policy_description:
        type: string
        required: true
        title: "Policy Description"
        description: "Description of the Data Flow users policy"

      application_file_uri:
        type: string
        title: "Application file URI"
        visible:
            and:
              - not:
                - deploy_demo_application
              - show_advanced

      arguments:
        type: string
        title: "Application arguments"
        visible:
            and:
              - not:
                - deploy_demo_application 
              - show_advanced

      application_archive_uri:
        type: string
        title: "Application archive URI"
        visible: show_advanced

      application_display_name:
        type: string
        title: "Application display name"
        visible: show_advanced

      application_driver_shape:
        type: oci:core:instanceshape:name
        title: "Application driver shape"
        visible: show_advanced
        dependsOn:
          compartmentId: ${compartment_ocid}

      application_executor_shape:
        type: oci:core:instanceshape:name
        title: "Application executor shape"
        visible: show_advanced
        dependsOn:
          compartmentId: ${compartment_ocid}

      application_language:
        type: string
        title: "Application language"
        visible: show_advanced

      application_num_executors:
        type: string
        title: "Number of application executors"
        visible: show_advanced

      application_spark_version:
        type: string
        title: "Spark version"
        visible: show_advanced